default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hr-til_development

test: &test
  <<: *default
  database: hr-til_test

cucumber:
  <<: *test

staging:
  <<: *default
  database: hr-til_development

production:
  <<: *default
  url: postgres://zczpgamspjbdiq:XxWsODPs62pI-a-de9WrG8Nwm-@ec2-54-235-145-226.compute-1.amazonaws.com:5432/dckcpf4s2t2vt3
